image: docker:git

services:
  - docker:dind

variables:
  REGISTRY: registry.gitlab.com
  IMAGE: $REGISTRY/andreas_resch/suedtirol1-tracker-api
  DOCKER_SERVICE_NAME: suedtirol1-tracker-api

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
  script:
    - docker pull $IMAGE:latest || true
    - docker pull $IMAGE:build-stage || true
    - docker build --target build-stage --cache-from $IMAGE:build-stage -t $IMAGE:build-stage .
    - docker build --target runtime-stage --cache-from $IMAGE:build-stage --cache-from $IMAGE:latest -t $IMAGE:latest -t $IMAGE:latest .
    - docker push $IMAGE:latest
    - docker push $IMAGE:build-stage

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - mkdir -p /root/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa

  script:
    - SETUP="cd ~/container/andreas"
    - LOGIN="docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY"
    - PULL="docker-compose -f docker-compose.yml pull --quiet"
    - BUILD="docker-compose -f docker-compose.yml up -d $DOCKER_SERVICE_NAME"
    - ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no deploy@${SERVER_URL} "$SETUP && $LOGIN && $PULL && $BUILD"

